services:
  db:
    image: mysql:latest
    container_name: stream_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=weather_app
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: